In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [13]:
df = pd.read_csv("theroid_dataset.csv")

In [12]:
df.head()

,Age,Sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid
0,0.45,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.61,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.75,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
X = df.drop("Outlier_label" , axis=1)
y = df["Outlier_label"]

KeyError: "['Outlier_label'] not found in axis"

In [9]:
df.head()

,Age,Sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid
0,0.45,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.61,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.75,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

NameError: name 'X' is not defined