In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
a = [2,3,4]

In [9]:
np.array(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c = a

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0] =  100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d =np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a[1]= 400

In [23]:
a

array([100, 400,   3,   4])

In [24]:
#generating array from function
np.fromfunction(lambda i , j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i ,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable ,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('234 234' , sep=' ')

array([234., 234.])

In [35]:
np.fromstring('4,5' , sep=' ,')

array([4., 5.])

In [36]:
#Numpy =Data types

In [37]:
l = [2,3,4,6]

In [38]:
ar =np.array(l)

In [39]:
ar

array([2, 3, 4, 6])

In [40]:
ar.ndim #tell dimension

1

In [44]:
arr2 =np.array([[1,2,3,4] , [2,3,4,5]])

In [45]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [46]:
arr2.ndim

2

In [47]:
ar.size

4

In [48]:
arr2.size

8

In [49]:
ar.shape

(4,)

In [50]:
arr2.shape

(2, 4)

In [52]:
ar.dtype

dtype('int64')

In [53]:
arr2.dtype

dtype('int64')

In [54]:
ar22 = np.array([(1.4,45,45) ,(23,45,66)])

In [55]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [56]:
ar22.dtype

dtype('float64')

In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(np.arange(2.3,5.6,.3)) # convert into function

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [62]:
np.linspace(1,5,10) # data generator function

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
arr4=np.zeros((3,4,2,3))

In [70]:
arr4.ndim

4

In [71]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [72]:
np.ones(4)

array([1., 1., 1., 1.])

In [73]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
on = np.ones((2,3,2))

In [77]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [78]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [80]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [81]:
np.eye(4) #create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
np.linspace(2,4 ,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [84]:
np.logspace(2,5 ,10 , base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [85]:
#generte data

In [87]:
arr = np.random.randn(3,4)

In [88]:
import pandas as pd

In [89]:
pd.DataFrame(arr)

          0         1         2         3
0  1.527213  0.013095  0.973439  1.388089
1  1.521239  0.570013 -0.207111  0.142689
2  0.964403 -0.580747  0.321443 -0.200200

In [91]:
arr6 = np.random.rand(3,4)

In [92]:
pd.DataFrame(arr6)

          0         1         2         3
0  0.199354  0.445044  0.889918  0.261630
1  0.508353  0.099004  0.811836  0.805847
2  0.943295  0.198990  0.748729  0.820883

In [93]:
arr6

array([[0.19935399, 0.44504405, 0.8899184 , 0.26163045],
       [0.50835299, 0.09900354, 0.81183562, 0.80584718],
       [0.94329507, 0.19899019, 0.748729  , 0.82088346]])

In [107]:
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv("test.csv") #it is used to saved in data form

In [108]:
pd.DataFrame(arr8)

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,34,9,88,94,25,109,89,9,102,38,...,109,67,54,7,39,43,1,15,58,21
1,75,69,65,54,64,101,109,46,1,33,...,42,49,41,30,55,49,24,44,38,83
2,70,56,19,54,43,60,30,26,77,43,...,68,92,54,68,45,62,24,70,107,51
3,24,103,38,77,68,22,5,72,78,93,...,13,78,24,71,8,71,70,79,88,59
4,28,34,108,27,36,23,68,71,100,46,...,7,30,37,101,1,29,109,97,25,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,47,76,29,20,76,40,65,81,96,50,...,105,8,42,46,100,81,39,43,42,71
296,11,23,67,107,25,29,45,31,101,44,...,12,4,81,90,8,103,26,100,54,17
297,34,9,51,58,88,95,99,6,38,22,...,68,68,95,33,99,8,106,101,69,31
298,90,3,68,94,56,59,87,87,68,106,...,46,20,95,58,88,38,88,35,38,64
299,105,71,24,60,89,93,30,103,12,42,...,6,35,91,34,37,91,85,73,35,22

In [101]:
arr8

array([[ 34,   9,  88, ...,  15,  58,  21],
       [ 75,  69,  65, ...,  44,  38,  83],
       [ 70,  56,  19, ...,  70, 107,  51],
       ...,
       [ 34,   9,  51, ..., 101,  69,  31],
       [ 90,   3,  68, ...,  35,  38,  64],
       [105,  71,  24, ...,  73,  35,  22]], shape=(300, 400), dtype=int32)

In [117]:
arr1 = np.random.rand(3,4)

In [118]:
arr1

array([[0.14525439, 0.13430414, 0.52249099, 0.25421087],
       [0.8588986 , 0.58671796, 0.86900607, 0.55354332],
       [0.41340405, 0.31015204, 0.19357042, 0.31335459]])

In [119]:
arr1.reshape(6,2)

array([[0.14525439, 0.13430414],
       [0.52249099, 0.25421087],
       [0.8588986 , 0.58671796],
       [0.86900607, 0.55354332],
       [0.41340405, 0.31015204],
       [0.19357042, 0.31335459]])

In [123]:
pd.DataFrame(arr1)

          0         1         2         3
0  0.145254  0.134304  0.522491  0.254211
1  0.858899  0.586718  0.869006  0.553543
2  0.413404  0.310152  0.193570  0.313355

In [122]:
arr1[1][1]

np.float64(0.5867179634159235)

In [128]:
arr1[2:5 ,1]

array([0.31015204])

In [130]:
arr =  np.random.randint(1,100,(5,5))

In [131]:
arr

array([[74, 58, 46, 31,  3],
       [60, 86, 76, 86, 27],
       [53, 87, 56, 54,  4],
       [ 7, 60,  9, 70, 96],
       [54, 60, 32, 28, 22]], dtype=int32)

In [133]:
arr[arr>50]

array([74, 58, 60, 86, 76, 86, 53, 87, 56, 54, 60, 70, 96, 54, 60],
      dtype=int32)

In [134]:
arr

array([[74, 58, 46, 31,  3],
       [60, 86, 76, 86, 27],
       [53, 87, 56, 54,  4],
       [ 7, 60,  9, 70, 96],
       [54, 60, 32, 28, 22]], dtype=int32)

In [135]:
arr[2:4 ,[1,2]]

array([[87, 56],
       [60,  9]], dtype=int32)

In [136]:
arr[0][0] = 5000

In [137]:
arr

array([[5000,   58,   46,   31,    3],
       [  60,   86,   76,   86,   27],
       [  53,   87,   56,   54,    4],
       [   7,   60,    9,   70,   96],
       [  54,   60,   32,   28,   22]], dtype=int32)

In [141]:
arr1 =np.random.randint(1,3 ,(3,3))
arr2 =np.random.randint(1,3 , (3,3))

In [142]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [2, 1, 2]], dtype=int32)

In [143]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 2]], dtype=int32)

In [144]:
arr1+arr2

array([[4, 3, 4],
       [3, 4, 4],
       [4, 2, 4]], dtype=int32)

In [145]:
arr1-arr2

array([[ 0, -1,  0],
       [-1,  0,  0],
       [ 0,  0,  0]], dtype=int32)

In [146]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [0.5, 1. , 1. ],
       [1. , 1. , 1. ]])

In [147]:
arr1*arr2

array([[4, 2, 4],
       [2, 4, 4],
       [4, 1, 4]], dtype=int32)

In [148]:
arr1@arr2 #gives @ matrix multiplictaion

array([[10,  8, 10],
       [10,  8, 10],
       [10,  8, 10]], dtype=int32)

In [149]:
arr1/0

C:\Users\panka\AppData\Local\Temp\ipykernel_2336\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [150]:
arr1+100

array([[102, 101, 102],
       [101, 102, 102],
       [102, 101, 102]], dtype=int32)

In [151]:
arr1**2

array([[4, 1, 4],
       [1, 4, 4],
       [4, 1, 4]], dtype=int32)

In [152]:
#broadcasting in numpy

In [153]:
arr = np.zeros((4,4))

In [154]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [155]:
row = np.array([1,2,3,4])

In [156]:
row

array([1, 2, 3, 4])

In [157]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [158]:
row.T

array([1, 2, 3, 4])

In [159]:
col = np.array([[1,2,3,4]])

In [161]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [162]:
col

array([[1, 2, 3, 4]])

In [164]:
arr9 = np.random.randint(1,4,(3,4))

In [165]:
np.sqrt(arr9)

array([[1.73205081, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        , 1.73205081],
       [1.41421356, 1.41421356, 1.        , 1.41421356]])

In [166]:
arr9

array([[3, 2, 2, 2],
       [2, 2, 1, 3],
       [2, 2, 1, 2]], dtype=int32)

In [167]:
np.exp(arr9)

array([[20.08553692,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 ,  2.71828183, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ]])

In [168]:
np.log2(arr9)

array([[1.5849625, 1.       , 1.       , 1.       ],
       [1.       , 1.       , 0.       , 1.5849625],
       [1.       , 1.       , 0.       , 1.       ]])