In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,LabelEncoder
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix , classification_report,mean_squared_error

In [4]:
#Dataset creation
data = {
    "Age" :[21,25,30,35,40,45],
    "Salary" : [2000,3000,45000,5656,5688,2345],
    "Buy" :[0,0,0,1,1,1]
}
df = pd.DataFrame(data)

   Age  Salary  Buy
0   21    2000    0
1   25    3000    0
2   30   45000    0
3   35    5656    1
4   40    5688    1
5   45    2345    1

In [7]:
df

   Age  Salary  Buy
0   21    2000    0
1   25    3000    0
2   30   45000    0
3   35    5656    1
4   40    5688    1
5   45    2345    1

In [9]:
#Train_test_split
X = df[["Age" , "Salary"]]
y = df["Buy"]

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size = 0.2 , random_state =42)

In [10]:
#Feature scaling
scaler = StandardScaler()

X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
X_train

   Age  Salary
5   45    2345
2   30   45000
4   40    5688
3   35    5656

In [13]:
X_test

   Age  Salary
0   21    2000
1   25    3000

In [15]:
#Linear regression
model = LinearRegression()
model.fit(X_train , y_train)

y_pred = model.predict(X_test)

print("MSE:" , mean_squared_error(y_test,y_pred))

MSE: 1.4436092629119015

In [18]:
#Logistic regression(classification)

model = LogisticRegression()
model.fit(X_train_scaled , y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy" , accuracy_score(y_test,y_pred))

Accuracy 0.0

In [21]:
#Decision tree
model = DecisionTreeClassifier()
model.fit(X_train , y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[0 2]
 [0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\panka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])